import { make } from "@restdk/shared";
import {
  injectLib,
  injectEnv,
  injectRequest,
  injectBaseModel,
  injectTools,
} from "../helper/inject";
import { Model } from "./Model";

export class Restdk {
  name: string;
  baseURL: string;
  env: string;

  models: Model[];

  getModelString() {
    return this.models.map((model) => "export " + model).join("\n");
  }

  toString() {
    return `
      ${injectLib()}
      /*
      This file is automatically generated. Do not modify it.
      */
      ${injectEnv()}
      ${injectRequest(this)}
      ${injectBaseModel()}
      ${injectTools()}
      ${this.getModelString()}
    `;
  }

  static create(props: Partial<Restdk>): Restdk {
    return make(new Restdk(), props);
  }
}
